controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    range_sensor_broadcaster:
      type: range_sensor_broadcaster/RangeSensorBroadcaster

    gpio_controller:
      type: gpio_controllers/GpioCommandController

range_sensor_broadcaster:
  ros__parameters:
    sensor_name: "base_tof_sensor_1_joint"
    frame_id: "tof_sensor_1_link"
    radiation_type: 1
    field_of_view: 0.467
    max_range: 4.0
    min_range: 0.005

gpio_controller:
  ros__parameters:
    gpios:
      - base_tof_sensor_1_settings

    command_interfaces:
      base_tof_sensor_1_settings:
        interfaces:
          - mode
          - calibration
          - sample_rate
          - needs_calibration

    state_interfaces:
      base_tof_sensor_1_settings:
        interfaces:
          - mode
          - calibration
          - sample_rate
          - needs_calibration
